[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python3 app.py"
